### ISSUE TITLE
Desktop crashes to monitor on GS CFFA with 3+ volumes

### ISSUE THREAD

**Issue by JohnMBrooks** [inexorabletash/a2d#45] opened 2018-01-27 08:20 UTC
Desktop boots normally and allows user input (click menus, etc). After a couple seconds Desktop crashes to the monitor. I suspect Desktop is crashing trying to directly call the device driver for the 3rd CFFA smartport volume which has been remapped by ProDOS 2.x to an empty slot.

The crash does not happen with ProDOS 1.x, or if the CFFA is restricted to mounting only 2 volumes.

**Comment by inexorabletash** [comment] 2018-01-27 16:19
Yep - the code to determine the device type (ProFile, etc) accesses the "slot" directly by decoding the unit number in DEVLIST rather than following the protocol in Tech Note 21. Same root cause as issue #6

**Comment by inexorabletash** [comment] 2018-11-15 16:57
Specifically, this is at:

https://github.com/inexorabletash/a2d/blob/master/desktop/desktop_main.s#L774

For remapped drives, this is bogus. Per @mgcaret on csa2p ... may be unsalvageable?

**Comment by mgcaret** [comment] 2018-11-15 18:52
Yeah that bit is going to be a problem since it's trying to decide if a disk has been inserted.  This is also the code that makes the IIc Plus 3.5" drives spin a lot.

There are a few options for determining disk insertion state for disks that can't be mapped to a slot:

(1) Use the ON_LINE call to determine the status of the drive.  This may have undesirable effects.
(2) Issue the STATUS call to the driver address in the Global Page.  Per 6.3 of the P8 TRM, the status call will return with carry set if the disk is not ready for READ+WRITE.  If carry is clear, there is a disks.  If the error returned indicates write-protected, then a disk in inserted.  Anything else and we can assume there is no disk.  This may have undesirable consequences.
(3) Check for a disk once when desktop loads (via one of the options above), and again only when the user selects the "Check Drives" menu option.
(4) Find a workaround that doesn't need what is currently esoteric knowledge (seems unlikely).

I think that (1) or (2) are the immediately feasible options, though on a IIc Plus I'd fall back to (3) for everything on the SmartPort that we can't confirm is not a 3.5" drive.

I had considered that since the number of ProDOS versions using SmartPort remapping is currently very small, we can possibly figure out the real slot number from the internal mapping table.  However that would be a problem.

ProDOS 2.0.3 keeps the remapped unit numbers at $D6F0.  Because of a conditional assembly option, it is possible that a version before 2.0.3 put them at $FD6F instead, but I am not sure.  2.0.3 keeps the SmartPort entry addresses for remapped drives at $FD6F (low bytes) and $FD7E (high bytes).  If a previous version used $FD6F for the unit numbers, then those tables are offset +15 bytes.

Unfortunately, the entry address tables do move, for instance in 2.4.1 they are at $FD52 and $FD61.

(3) @JohnMBrooks for 2.5+ maybe we can supply a way to figure out where the remapping tables are.  We'd need 4 bytes in the global page or another well-defined location to hold the addresses of the unit numbers table and the SP entry tables. 

A really awesome solution would be a new MLI call that could return the SP entry address and unit number for a remapped drive, but that's likely a 3.x-ish thing.

**Comment by inexorabletash** [comment] 2018-11-15 23:52
Option (3) is sufficient for my needs in the short term, given that I'm usually dealing with removable media (real or virtual) only in Disk II drives.

It's possible this root cause is also the reason I see occasional lock-ups on my Laser 128EX + Floppy Emu setup with 3 SmartPort HDs. I'll give neutering this code a try and see if it improves stability there.

**Comment by inexorabletash** [comment] 2018-12-27 02:31
In the `master` branch, most SmartPort accesses are now done via correct driver address lookups, no more trusting unit numbers for slot/drive. That may have fixed this - can anyone give it a whirl?

The semi-distinct Disk Copy system is not updated, and I may have missed other sketchy code in overlays.

**Comment by inexorabletash** [comment] 2019-01-06 23:15
At least in GSplus, this appears to be solved (again, for DeskTop itself, not the Disk Copy module)

Closing out for now.

**Closed by inexorabletash** 2019-01-06 23:15 UTC
Labels: DeskTop, bug, root-cause-identified
